name: cleanup space

on:
#  release:
#    types: published
  push:
    paths:
      - '.github/workflows/cleanup.yml'
  watch:
    types: started

env:
  SSH_ACTIONS: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
        /bin/bash ./script/free_disk_space.sh

    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Make script executable
      run: chmod +x .github/workflows/purge_artifacts.sh

    - name: cleanup old action artifacts
      run: .github/workflows/purge_artifacts.sh ${{ secrets.RELEASES_TOKEN }}

